enum TokenType {
    KEYWORD = "KEYWORD",
    BOOLEAN = "BOOLEAN",
    OPERATOR = "OPERATOR",
    UNARY_OPERATOR = "UNARY_OPERATOR",
    IDENTIFIER = "IDENTIFIER",
    STRING = "STRING",
    F_STRING = "F-STRING",
    BACKTICK_STRING = "BACKTICK_STRING",
    NUMBER = "NUMBER",
    SYMBOL = "SYMBOL",
    WHITESPACE = "WHITESPACE",
    COMMENT = "COMMENT",
    EOF = "EOF",
}
export default TokenType;
